### ISSUE TITLE
如何用啊，大佬，给个包或者插件吧，我不外泄，真自己用

### ISSUE THREAD

**Issue by laodijituan** [koto-aya/feilu_scrapy#1]
如何用啊，大佬，给个包或者插件吧，我不外泄，真自己用

**Comment by koto-aya** [comment]
你加我qq吧，740969457

**Comment by peng-alan** [comment]
我自己下载研究了半天了，加了oss2，加了scrapy，还下了个mysql，结果最后还是没有弄明白大佬的代码逻辑，能加个好友吗？大佬，我也想要一个可执行包....
